on:
  workflow_call:
    inputs:
      base_ref:
        type: string
        required: true
      head_ref:
        type: string
        required: true

jobs:
  do_reusable_thing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.base_ref }}
      - run: |
          echo "base_ref whoami: $(cat whoami.wtf)"
          echo "TIMESTAMP=$(date -u +%N)" >>"$GITHUB_ENV"
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.head_ref }}
      - run: |
          echo "head_ref whoami: $(cat whoami.wtf)"
          if [ "$TIMESTAMP" == "$(date -u +%N)" ]; then
            echo 'well that seems very unlikely'
            exit 1
          fi
