on:
  pull_request:
    branches:
      - main

jobs:
  use_reusable_thing:
    if: github.event.pull_request.draft == false
    uses: efjacobson/scratch/.github/workflows/reusable.yaml@main
    with:
      head_ref: ${{ github.event.pull_request.head.ref }}
      base_ref: ${{ github.event.pull_request.base.ref }}
