name: test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.2
        with:
          repository: '${{ github.repository }}.wiki'
      - name: log
        run: |
          echo "$GITHUB_REPOSITORY"
          pwd
          ls
