name: 'log'

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'bar'
        required: true
        default: 'baz'

jobs:
  log:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'dolog'
        run: |
          echo "github: ${{ toJson(github) }}"
          echo "env: ${{ toJson(env) }}"
          echo "vars: ${{ toJson(vars) }}"
          echo "job: ${{ toJson(job) }}"
          echo "steps: ${{ toJson(steps) }}"
          echo "runner: ${{ toJson(runner) }}"
          echo "strategy: ${{ toJson(strategy) }}"
          echo "matrix: ${{ toJson(matrix) }}"
          echo "needs: ${{ toJson(needs) }}"
          echo "inputs: ${{ toJson(inputs) }}"
