name: 'log'

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'bar'
        required: true
        default: 'baz'

jobs:
  log:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'dolog'
        shell: bash -euxo pipefail
        run: |
          echo "hI"
          ls
          echo "good times"
          ls
