name: test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout wiki
        run: |
          echo "$GITHUB_REPOSITORY"
