name: test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3.5.2
        with:
          repository: ${{ github.repository }}
          path: repo
      - name: checkout-wiki
        uses: actions/checkout@v3.5.2
        with:
          repository: '${{ github.repository }}.wiki'
          path: wiki
      - name: log
        run: |
          ls -laR
