on:
  pull_request:
    branches:
      - master
      - main

jobs:
  test-thing:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: |
          echo "TIMESTAMP=$(date -u +%N)" >>"$GITHUB_ENV"
      - uses: actions/checkout@v3
      - run: |
          if [ "$TIMESTAMP" == "$(date -u +%N)" ]; then
            echo 'well that seems very unlikely'
            exit 1
          fi
