name: 'log'

on:
  workflow_dispatch:
    inputs:
      foo:
        description: 'bar'
        required: true
        default: 'baz'

jobs:
  log:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'dolog'
        run: |
          set -x
          echo "hI"
          echo "good times"
