on:
  workflow_call:
    inputs:
      default_branch:
        type: string
        required: false
        default: main

jobs:
  test-thing:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.default_branch }}
      - run: |
          echo "TIMESTAMP=$(date -u +%N)" >>"$GITHUB_ENV"
      - uses: actions/checkout@v3
      - run: |
          if [ "$TIMESTAMP" == "$(date -u +%N)" ]; then
            echo 'well that seems very unlikely'
            exit 1
          fi
